//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Soup.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let Soup = _ModuleRegistry.module("Soup");

    Slice.defineSequence(Soup, "songdatasHelper", "Ice.ByteHelper", true);

    Soup.Song = class
    {
        constructor(id = 0, title = "", author = "", extension = "")
        {
            this.id = id;
            this.title = title;
            this.author = author;
            this.extension = extension;
        }

        _write(ostr)
        {
            ostr.writeInt(this.id);
            ostr.writeString(this.title);
            ostr.writeString(this.author);
            ostr.writeString(this.extension);
        }

        _read(istr)
        {
            this.id = istr.readInt();
            this.title = istr.readString();
            this.author = istr.readString();
            this.extension = istr.readString();
        }

        static get minWireSize()
        {
            return  7;
        }
    };

    Slice.defineStruct(Soup.Song, true, true);

    Slice.defineSequence(Soup, "SongsHelper", "Soup.Song", false);

    const iceC_Soup_MusicLibrary_ids = [
        "::Ice::Object",
        "::Soup::MusicLibrary"
    ];

    Soup.MusicLibrary = class extends Ice.Object
    {
    };

    Soup.MusicLibraryPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Soup.MusicLibrary, Soup.MusicLibraryPrx, iceC_Soup_MusicLibrary_ids, 1,
    {
        "addSong": [, , , , , [[7], [7], [7], ["Soup.songdatasHelper"]], , , , ],
        "removeSong": [, , , , , [[Soup.Song]], , , , ],
        "updateSong": [, , , , , [[Soup.Song], ["Soup.songdatasHelper"]], , , , ],
        "searchByTitle": [, , , , ["Soup.SongsHelper"], [[7]], , , , ],
        "searchByAuthor": [, , , , ["Soup.SongsHelper"], [[7]], , , , ]
    });
    exports.Soup = Soup;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
